<?php
declare(strict_types=1);

namespace Spices\Spice;
use Spices\Spice;

class Salt extends Spice{
    public function getColor(): string
    {
        return "white";
    }
    public function getName(): string
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }
}