<?php
declare(strict_types=1);

namespace Spices\Spice;
use Spices\Spice;

class Vegeta extends Spice {
    public function getColor(): string
    {
        return "orange".PHP_EOL;
    }
    public function getName(): string
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }
}